In [1]:
import pandas as pd 
import numpy as np

df = pd.read_excel('fixed_company.xlsx')
df.head()

,Unnamed: 0,name,phone,company,state,link
0,0,Mario Manetta,(727) 239-6102,Tampa Bay Business Group,"St. Petersburg,Florida",https://www.bizbuysell.com/business-broker/mar...
1,1,Dan Soronen,(727) 580-9937,Main Street & Main,"Saint Petersburg,Florida",https://www.bizbuysell.com/business-broker/dan...
2,2,Gregg Potter,(727) 656-3331,Legacy Venture Group & BuyBIzUSA,"Brandon,Florida",https://www.bizbuysell.com/business-broker/gre...
3,3,Jary Jackson,(910) 703-0437,"Florida Business Exchange, Inc.","Volusia County, FL",https://www.bizbuysell.com/business-broker/jar...
4,4,Maria Cayuela,(754) 707-4881,Withal Realty,"Broward County, FL",https://www.bizbuysell.com/business-broker/mar...

In [2]:
del df['Unnamed: 0']
df.head()

,name,phone,company,state,link
0,Mario Manetta,(727) 239-6102,Tampa Bay Business Group,"St. Petersburg,Florida",https://www.bizbuysell.com/business-broker/mar...
1,Dan Soronen,(727) 580-9937,Main Street & Main,"Saint Petersburg,Florida",https://www.bizbuysell.com/business-broker/dan...
2,Gregg Potter,(727) 656-3331,Legacy Venture Group & BuyBIzUSA,"Brandon,Florida",https://www.bizbuysell.com/business-broker/gre...
3,Jary Jackson,(910) 703-0437,"Florida Business Exchange, Inc.","Volusia County, FL",https://www.bizbuysell.com/business-broker/jar...
4,Maria Cayuela,(754) 707-4881,Withal Realty,"Broward County, FL",https://www.bizbuysell.com/business-broker/mar...

In [3]:
company_null = df[df['company'].isnull()]
company_null.head()

,name,phone,company,state,link
6959,Peter Rook,(636) 675-2103,NaN,"Saint Louis County, MO",https://www.bizbuysell.com/business-broker/pet...
7148,Brian Smith,(908) 409-1900,NaN,"Montclair,New Jersey",https://www.bizbuysell.com/business-broker/bri...
7193,BizEx Business Brokers,NaN,NaN,NaN,https://www.bizbuysell.com/business-broker/biz...
7194,Mani Singh,NaN,NaN,NaN,https://www.bizbuysell.com/business-broker/man...
7195,"Houmehr ""Mike"" Panoussi",NaN,NaN,NaN,https://www.bizbuysell.com/business-broker/hou...

In [4]:
print(len(company_null))

34

In [5]:
from selenium import webdriver
from bs4 import BeautifulSoup 
import time 

company_null_list = []
count = 0 

for url in company_null['link']:
    driver = webdriver.Chrome()
    driver.get(url)
    time.sleep(5)
    page = driver.page_source
    soup = BeautifulSoup(page, 'html.parser')

    try:
        location = soup.find('span', {'class': "f-m margin-b-8 block normal"})
        company = location.get_text(strip=True)
    except:
        print(count, 'N/A')
        count += 1
        company_null_list.append(np.nan)
    else:
        print(count, company)
        count += 1
        company_null_list.append(company)

print(company_null_list)

0 N/A
1 N/A
2 BizEx Businesss Brokers
3 TNW Business Brokers
4 Liberty Business Advisors
5 Vanguard Properties
6 Mossy Oak Properties Alaska Wasilla
7 Transworld Business Advisors of Alaska
8 Kachemak Keller Williams Realty Alaska Group
9 Transworld Business Advisors of Alaska
10 BHHS Drysdale Properties
11 Homesmart Realty West
12 Team Spirit Realty
13 Doctors Broker LLC
14 Northcap Commercial
15 Pool Route Brokers, Inc.
16 Senior Housing Group
17 Realty One Group Future
18 Premier Realty
19 Golden State Laundry Systems in Association with Edge Realty
20 RedPoint Realty
21 Pryia International Inc.
22 Northern Edge
23 Rix Business Sales
24 Dream Realty
25 Business Sales & Acquisitions, West USA Realty
26 iMatch Franchise and Global Investments
27 Transworld Phoenix
28 wci commercial
29 Tucson Business Investments
30 Business Brokers of Arizona
31 Strategic Medical Brokers LLC
32 HUB Commercial | Arizona Restaurant Sales
33 American Realty Brokers
[nan, nan, 'BizEx Businesss Brokers', 'TNW Business Brokers', 'Liberty Business Advisors', 'Vanguard Properties', 'Mossy Oak Properties Alaska Wasilla', 'Transworld Business Advisors of Alaska', 'Kachemak Keller Williams Realty Alaska Group', 'Transworld Business Advisors of Alaska', 'BHHS Drysdale Properties', 'Homesmart Realty West', 'Team Spirit Realty', 'Doctors Broker LLC', 'Northcap Commercial', 'Pool Route Brokers, Inc.', 'Senior Housing Group', 'Realty One Group Future', 'Premier Realty', 'Golden State Laundry Systems in Association with Edge Realty', 'RedPoint Realty', 'Pryia International Inc.', 'Northern Edge', 'Rix Business Sales', 'Dream Realty', 'Business Sales & Acquisitions, West USA Realty', 'iMatch Franchise and Global Investments', 'Transworld Phoenix', 'wci commercial', 'Tucson Business Investments', 'Business Brokers of Arizona', 'Strategic Medical Brokers LLC', 'HUB Commercial | Arizona Restaurant Sales', 'American Realty Brokers']

In [6]:
del company_null['company'] 
company_null.head()

,name,phone,state,link
6959,Peter Rook,(636) 675-2103,"Saint Louis County, MO",https://www.bizbuysell.com/business-broker/pet...
7148,Brian Smith,(908) 409-1900,"Montclair,New Jersey",https://www.bizbuysell.com/business-broker/bri...
7193,BizEx Business Brokers,NaN,NaN,https://www.bizbuysell.com/business-broker/biz...
7194,Mani Singh,NaN,NaN,https://www.bizbuysell.com/business-broker/man...
7195,"Houmehr ""Mike"" Panoussi",NaN,NaN,https://www.bizbuysell.com/business-broker/hou...

In [7]:
company_null['company'] = company_null_list 
company_null.head()

/var/folders/5p/nlt6bn5j1j5dt69qrb8949sh0000gn/T/ipykernel_28188/3042267564.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  company_null['company'] = company_null_list

,name,phone,state,link,company
6959,Peter Rook,(636) 675-2103,"Saint Louis County, MO",https://www.bizbuysell.com/business-broker/pet...,NaN
7148,Brian Smith,(908) 409-1900,"Montclair,New Jersey",https://www.bizbuysell.com/business-broker/bri...,NaN
7193,BizEx Business Brokers,NaN,NaN,https://www.bizbuysell.com/business-broker/biz...,BizEx Businesss Brokers
7194,Mani Singh,NaN,NaN,https://www.bizbuysell.com/business-broker/man...,TNW Business Brokers
7195,"Houmehr ""Mike"" Panoussi",NaN,NaN,https://www.bizbuysell.com/business-broker/hou...,Liberty Business Advisors

In [8]:
df = df.dropna(subset = ['company'])
print(len(df))

7191

In [9]:
df = pd.concat([df, company_null], ignore_index = True)
print(len(df))

7225

In [10]:
df.to_excel('company2.xlsx')

In [11]:
df.isnull().sum()

name         0
phone      471
company      2
state      440
link         0
dtype: int64

In [13]:
company2 = df[df['company'].isnull()]
display(company2)

,name,phone,company,state,link
7191,Peter Rook,(636) 675-2103,NaN,"Saint Louis County, MO",https://www.bizbuysell.com/business-broker/pet...
7192,Brian Smith,(908) 409-1900,NaN,"Montclair,New Jersey",https://www.bizbuysell.com/business-broker/bri...