In [1]:
import pandas as pd 
import numpy as np 

df = pd.read_excel('official1.xlsx')
del df['Unnamed: 0']
df.head()

,name,phone,company,state,link
0,Mario Manetta,(727) 239-6102,Tampa Bay Business Group,"St. Petersburg,Florida",https://www.bizbuysell.com/business-broker/mar...
1,Dan Soronen,(727) 580-9937,Main Street & Main,"Saint Petersburg,Florida",https://www.bizbuysell.com/business-broker/dan...
2,Gregg Potter,(727) 656-3331,Legacy Venture Group & BuyBIzUSA,"Brandon,Florida",https://www.bizbuysell.com/business-broker/gre...
3,Jary Jackson,(910) 703-0437,"Florida Business Exchange, Inc.","Volusia County, FL",https://www.bizbuysell.com/business-broker/jar...
4,Maria Cayuela,(754) 707-4881,Withal Realty,"Broward County, FL",https://www.bizbuysell.com/business-broker/mar...

In [2]:
df.shape

(7225, 5)

In [3]:
df.isnull().sum()

name         0
phone      471
company      0
state      440
link         0
dtype: int64

In [4]:
state_null = df[df['state'].isnull()]
print(len(state_null))
display(state_null)

440

,name,phone,company,state,link
4552,David Grahn,(205) 492-8598,Optics Capital LLC,NaN,https://www.bizbuysell.com/business-broker/dav...
4555,Greg Cook,(662) 554-5805,Alliant Capital Advisors LLC,NaN,https://www.bizbuysell.com/business-broker/gre...
4865,Patrick Marsch,(615) 544-5380,Pinson Group International,NaN,https://www.bizbuysell.com/business-broker/pat...
6785,Francois Takle,NaN,Coldwell Banker Hallmark Realty,NaN,https://www.bizbuysell.com/business-broker/fra...
6786,SUSAN Mehravar,NaN,Liberty Business Advisors,NaN,https://www.bizbuysell.com/business-broker/sus...
...,...,...,...,...,...
7220,Jon Barger,NaN,Tucson Business Investments,NaN,https://www.bizbuysell.com/business-broker/jon...
7221,Tony Gonzales,NaN,Business Brokers of Arizona,NaN,https://www.bizbuysell.com/business-broker/ton...
7222,Shaun Rudgear,NaN,Strategic Medical Brokers LLC,NaN,https://www.bizbuysell.com/business-broker/sha...
7223,Brian Harron,NaN,HUB Commercial | Arizona Restaurant Sales,NaN,https://www.bizbuysell.com/business-broker/bri...
7224,Mike Darmo,NaN,American Realty Brokers,NaN,https://www.bizbuysell.com/business-broker/mik...

In [5]:
from selenium import webdriver 
from bs4 import BeautifulSoup 
import time 

state_null_list = []
count = 0 

for url in state_null['link']:
    driver = webdriver.Chrome()
    driver.get(url)
    time.sleep(5)
    page = driver.page_source 
    soup = BeautifulSoup(page, 'html.parser')

    try:
        location = soup.find('span', {'id': 'ctl00_ctl00_Content_ContentPlaceHolder1_ctl02_ctl00_lblAreasServed'})
        state = location.get_text(strip=True)
    except:
        print(count, 'N/A')
        count += 1 
        state_null_list.append(np.nan)
    else:
        print(count, state)
        count += 1 
        state_null_list.append(state)

0 Jefferson County, AL
1 Limestone County, AL
2 Hamilton County, TN
3 Los Angeles County, CA
4 Contra Costa County, CA
5 Sacramento County, CA
6 Sacramento County, CA
7 Orange County, CA
8 Santa Clara County, CA
9 Los Angeles County, CA
10 Orange County, CA
11 Orange County, CA
12 Stanislaus County, CA
13 Orange County, CA
14 Los Angeles County, CA
15 San Diego County, CA
16 San Bernardino County, CA
17 Los Angeles County, CA
18 Santa Clara County, CA
19 Los Angeles County, CA
20 San Luis Obispo County, CA
21 Los Angeles County, CA
22 Los Angeles County, CA
23 Cook County, MN
24 Riverside County, CA
25 Santa Clara County, CA
26 Glenn County, CA
27 Los Angeles County, CA
28 San Diego County, CA
29 San Bernardino County, CA
30 Los Angeles County, CA
31 Sacramento County, CA
32 Los Angeles County, CA
33 Sacramento County, CA
34 Shasta County, CA
35 San Diego County, CA
36 Sacramento County, CA
37 Orange County, CA
38 Los Angeles County, CA
39 Contra Costa County, CA
40 Ventura County, CA
41 Los Angeles County, CA
42 San Bernardino County, CA
43 Los Angeles County, CA
44 San Luis Obispo County, CA
45 San Francisco County, CA
46 San Francisco County, CA
47 Orange County, CA
48 San Diego County, CA
49 Monterey County, CA
50 Orange County, CA
51 Stanislaus County, CA
52 San Diego County, CA
53 Orange County, CA
54 Sacramento County, CA
55 Santa Clara County, CA
56 San Diego County, CA
57 Orange County, CA
58 Maricopa County, AZ
59 Maricopa County, AZ
60 Maricopa County, AZ
61 Maricopa County, AZ
62 Maricopa County, AZ
63 Maricopa County, AZ
64 Maricopa County, AZ
65 Maricopa County, AZ
66 Maricopa County, AZ
67 Maricopa County, AZ
68 Contra Costa County, CA
69 Orange County, CA
70 San Diego County, CA
71 Los Angeles County, CA
72 San Francisco County, CA
73 Santa Clara County, CA
74 San Diego County, CA
75 San Diego County, CA
76 Orange County, CA
77 Shasta County, CA
78 Los Angeles County, CA
79 San Francisco County, CA
80 Los Angeles County, CA
81 Orange County, CA
82 Santa Clara County, CA
83 Placer County, CA
84 Placer County, CA
85 Maricopa County, AZ
86 Pima County, AZ
87 Coconino County, AZ
88 Pima County, AZ
89 Pima County, AZ
90 Maricopa County, AZ
91 Orange County, CA
92 Los Angeles County, CA
93 Los Angeles County, CA
94 Los Angeles County, CA
95 Santa Clara County, CA
96 Los Angeles County, CA
97 Los Angeles County, CA
98 Los Angeles County, CA
99 Riverside County, CA
100 Santa Clara County, CA
101 San Francisco County, CA
102 Los Angeles County, CA
103 Los Angeles County, CA
104 Sacramento County, CA
105 Los Angeles County, CA
106 Santa Clara County, CA
107 Orange County, CA
108 Orange County, CA
109 Los Angeles County, CA
110 Fresno County, CA
111 Los Angeles County, CA
112 Orange County, CA
113 San Diego County, CA
114 Orange County, CA
115 Los Angeles County, CA
116 Los Angeles County, CA
117 Los Angeles County, CA
118 Los Angeles County, CA
119 San Bernardino County, CA
120 San Bernardino County, CA
121 Sacramento County, CA
122 Santa Clara County, CA
123 Los Angeles County, CA
124 Orange County, CA
125 Los Angeles County, CA
126 San Diego County, CA
127 Orange County, CA
128 San Diego County, CA
129 San Francisco County, CA
130 San Diego County, CA
131 San Mateo County, CA
132 Santa Clara County, CA
133 San Diego County, CA
134 Los Angeles County, CA
135 Los Angeles County, CA
136 Stanislaus County, CA
137 Maricopa County, AZ
138 Maricopa County, AZ
139 Maricopa County, AZ
140 Gila County, AZ
141 Sacramento County, CA
142 Maricopa County, AZ
143 Maricopa County, AZ
144 Maricopa County, AZ
145 Cook County, MN
146 Los Angeles County, CA
147 Maricopa County, AZ
148 Riverside County, CA
149 Santa Clara County, CA
150 Los Angeles County, CA
151 Santa Clara County, CA
152 Orange County, CA
153 Santa Clara County, CA
154 Los Angeles County, CA
155 San Diego County, CA
156 Sonoma County, CA
157 San Bernardino County, CA
158 Los Angeles County, CA
159 San Mateo County, CA
160 Santa Barbara County, CA
161 Marin County, CA
162 Orange County, CA
163 Orange County, CA
164 San Diego County, CA
165 Stanislaus County, CA
166 San Diego County, CA
167 Marin County, CA
168 Merced County, CA
169 San Diego County, CA
170 Los Angeles County, CA
171 Los Angeles County, CA
172 Orange County, CA
173 San Diego County, CA
174 Los Angeles County, CA
175 San Francisco County, CA
176 Los Angeles County, CA
177 Los Angeles County, CA
178 Sutter County, CA
179 Los Angeles County, CA
180 Santa Clara County, CA
181 Los Angeles County, CA
182 Los Angeles County, CA
183 Los Angeles County, CA
184 Riverside County, CA
185 Santa Clara County, CA
186 Los Angeles County, CA
187 Los Angeles County, CA
188 Alameda County, CA
189 Alameda County, CA
190 Sacramento County, CA
191 Los Angeles County, CA
192 Sacramento County, CA
193 Los Angeles County, CA
194 Alameda County, CA
195 San Diego County, CA
196 Los Angeles County, CA
197 Orange County, CA
198 Santa Cruz County, CA
199 Los Angeles County, CA
200 Sacramento County, CA
201 San Diego County, CA
202 San Diego County, CA
203 San Diego County, CA
204 Los Angeles County, CA
205 Orange County, CA
206 Stanislaus County, CA
207 Los Angeles County, CA
208 Sacramento County, CA
209 Los Angeles County, CA
210 Los Angeles County, CA
211 Stanislaus County, CA
212 Santa Clara County, CA
213 Orange County, CA
214 San Diego County, CA
215 Santa Cruz County, CA
216 Orange County, CA
217 San Diego County, CA
218 Sonoma County, CA
219 Orange County, CA
220 Shasta County, CA
221 Los Angeles County, CA
222 Santa Clara County, CA
223 Placer County, CA
224 Los Angeles County, CA
225 Santa Clara County, CA
226 Riverside County, CA
227 San Diego County, CA
228 Los Angeles County, CA
229 Stanislaus County, CA
230 CA
231 CA
232 Los Angeles County, CA
233 Maricopa County, AZ
234 Maricopa County, AZ
235 Mohave County, AZ
236 Mohave County, AZ
237 Pima County, AZ
238 Mohave County, AZ
239 Orange County, CA
240 Los Angeles County, CA
241 Clark County, NV
242 Clark County, NV
243 Johnson County, KS
244 Sacramento County, CA
245 Alameda County, CA
246 Clark County, NV
247 Los Angeles County, CA
248 Orange County, CA
249 Contra Costa County, CA
250 Santa Cruz County, CA
251 Alameda County, CA
252 San Diego County, CA
253 Los Angeles County, CA
254 Orange County, CA
255 Los Angeles County, CA
256 Sacramento County, CA
257 San Diego County, CA
258 San Diego County, CA
259 San Diego County, CA
260 Marin County, CA
261 Orange County, CA
262 Los Angeles County, CA
263 Orange County, CA
264 Los Angeles County, CA
265 Sacramento County, CA
266 San Diego County, CA
267 Contra Costa County, CA
268 Santa Clara County, CA
269 Sacramento County, CA
270 Los Angeles County, CA
271 Orange County, CA
272 Los Angeles County, CA
273 San Francisco County, CA
274 San Diego County, CA
275 Los Angeles County, CA
276 Riverside County, CA
277 Los Angeles County, CA
278 Santa Clara County, CA
279 Santa Cruz County, CA
280 Limestone County, AL
281 Jefferson County, AL
282 Calhoun County, AL
283 Jefferson County, AL
284 Benton County, AR
285 Pulaski County, AR
286 Washington County, AR
287 Sebastian County, AR
288 Placer County, CA
289 Ventura County, CA
290 Orange County, CA
291 Orange County, CA
292 Fresno County, CA
293 Los Angeles County, CA
294 Riverside County, CA
295 Kern County, CA
296 Riverside County, CA
297 San Diego County, CA
298 Sacramento County, CA
299 Alameda County, CA
300 Los Angeles County, CA
301 Orange County, CA
302 Orange County, CA
303 San Francisco County, CA
304 Alameda County, CA
305 Contra Costa County, CA
306 Riverside County, CA
307 Los Angeles County, CA
308 Alameda County, CA
309 Tulare County, CA
310 Contra Costa County, CA
311 Marin County, CA
312 Orange County, CA
313 Orange County, CA
314 San Diego County, CA
315 Stanislaus County, CA
316 San Diego County, CA
317 Marin County, CA
318 Merced County, CA
319 San Diego County, CA
320 Los Angeles County, CA
321 Orange County, CA
322 San Diego County, CA
323 San Francisco County, CA
324 Los Angeles County, CA
325 San Francisco County, CA
326 Sutter County, CA
327 Los Angeles County, CA
328 Santa Clara County, CA
329 Los Angeles County, CA
330 Los Angeles County, CA
331 Los Angeles County, CA
332 Riverside County, CA
333 Santa Clara County, CA
334 Los Angeles County, CA
335 Los Angeles County, CA
336 Alameda County, CA
337 Alameda County, CA
338 Sacramento County, CA
339 Sacramento County, CA
340 Los Angeles County, CA
341 Saint Louis County, MO
342 Franklin County, OH
343 Los Angeles County, CA
344 Orange County, CA
345 Santa Clara County, CA
346 San Diego County, CA
347 Orange County, CA
348 Maricopa County, AZ
349 San Mateo County, CA
350 San Diego County, CA
351 Orange County, CA
352 Ventura County, CA
353 San Diego County, CA
354 Orange County, CA
355 Orange County, CA
356 Kern County, CA
357 Riverside County, CA
358 Los Angeles County, CA
359 Riverside County, CA
360 Los Angeles County, CA
361 Hamilton County, TN
362 Jefferson County, AL
363 Jefferson County, AL
364 Wake County, NC
365 Shelby County, TN
366 Benton County, AR
367 Fulton County, GA
368 Baldwin County, AL
369 Contra Costa County, CA
370 Riverside County, CA
371 Riverside County, CA
372 Fentress County, TN
373 Alameda County, CA
374 Los Angeles County, CA
375 San Francisco County, CA
376 Los Angeles County, CA
377 Laramie County, WY
378 Los Angeles County, CA
379 Los Angeles County, CA
380 Sacramento County, CA
381 Orange County, CA
382 Orange County, CA
383 Riverside County, CA
384 San Bernardino County, CA
385 Los Angeles County, CA
386 Los Angeles County, CA
387 Los Angeles County, CA
388 Los Angeles County, CA
389 Los Angeles County, CA
390 Santa Clara County, CA
391 Los Angeles County, CA
392 Los Angeles County, CA
393 Santa Cruz County, CA
394 Orange County, CA
395 Orange County, CA
396 Los Angeles County, CA
397 Orange County, CA
398 Placer County, CA
399 Clackamas County, OR
400 Santa Clara County, CA
401 San Diego County, CA
402 San Bernardino County, CA
403 Sacramento County, CA
404 Riverside County, CA
405 Ventura County, CA
406 Washoe County, NV
407 San Francisco County, CA
408 Los Angeles County, CA
409 San Bernardino County, CA
410 Los Angeles County, CA
411 San Francisco County, CA
412 Kenai Peninsula County, AK
413 Anchorage County, AK
414 Kenai Peninsula County, AK
415 Anchorage County, AK
416 Sonoma County, CA
417 San Diego County, CA
418 Orange County, CA
419 Seminole County, FL
420 Clark County, NV
421 Orange County, CA
422 Sacramento County, CA
423 Alameda County, CA
424 Sacramento County, CA
425 Los Angeles County, CA
426 Orange County, CA
427 San Bernardino County, CA
428 New York County, NY
429 Los Angeles County, CA
430 Los Angeles County, CA
431 Maricopa County, AZ
432 Oklahoma County, OK
433 Apache County, AZ
434 Maricopa County, AZ
435 Pima County, AZ
436 Maricopa County, AZ
437 Maricopa County, AZ
438 Maricopa County, AZ
439 Maricopa County, AZ

In [7]:
del state_null['state']
state_null.head()

,name,phone,company,link
4552,David Grahn,(205) 492-8598,Optics Capital LLC,https://www.bizbuysell.com/business-broker/dav...
4555,Greg Cook,(662) 554-5805,Alliant Capital Advisors LLC,https://www.bizbuysell.com/business-broker/gre...
4865,Patrick Marsch,(615) 544-5380,Pinson Group International,https://www.bizbuysell.com/business-broker/pat...
6785,Francois Takle,NaN,Coldwell Banker Hallmark Realty,https://www.bizbuysell.com/business-broker/fra...
6786,SUSAN Mehravar,NaN,Liberty Business Advisors,https://www.bizbuysell.com/business-broker/sus...

In [8]:
state_null['state'] = state_null_list 
state_null.head()

/var/folders/5p/nlt6bn5j1j5dt69qrb8949sh0000gn/T/ipykernel_30745/1787129495.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  state_null['state'] = state_null_list

,name,phone,company,link,state
4552,David Grahn,(205) 492-8598,Optics Capital LLC,https://www.bizbuysell.com/business-broker/dav...,"Jefferson County, AL"
4555,Greg Cook,(662) 554-5805,Alliant Capital Advisors LLC,https://www.bizbuysell.com/business-broker/gre...,"Limestone County, AL"
4865,Patrick Marsch,(615) 544-5380,Pinson Group International,https://www.bizbuysell.com/business-broker/pat...,"Hamilton County, TN"
6785,Francois Takle,NaN,Coldwell Banker Hallmark Realty,https://www.bizbuysell.com/business-broker/fra...,"Los Angeles County, CA"
6786,SUSAN Mehravar,NaN,Liberty Business Advisors,https://www.bizbuysell.com/business-broker/sus...,"Contra Costa County, CA"

In [10]:
print(len(df))

7225

In [11]:
print(len(state_null))

440

In [12]:
df = df.dropna(subset=['state'])
print(len(df))

6785

In [13]:
df = pd.concat([df, state_null], ignore_index=True)
print(len(df))

7225

In [14]:
df.to_excel('official2.xlsx')

In [15]:
df.isnull().sum()

name         0
phone      471
company      0
state        0
link         0
dtype: int64